move2alf-war/src/main/java/eu/xenit/move2alf/core/dto/Cycle.java
package eu.xenit.move2alf.core.dto;

import java.util.Date;
import java.util.Set;

import eu.xenit.move2alf.common.IdObject;
import eu.xenit.move2alf.core.enums.ECycleState;

public class Cycle extends IdObject {
	private int id;
	
	private Date startDateTime;
	
	private Date endDateTime;
	
	private Job job;

	private Set<ProcessedDocument> processedDocuments;
	
	public Cycle() {
		
	}
	
	public void setId(int id){
		this.id = id;
	}
	
	public int getId(){
		return id;
	}

	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	public Date getStartDateTime() {
		return startDateTime;
	}

	public void setEndDateTime(Date endDateTime) {
		this.endDateTime = endDateTime;
	}

	public Date getEndDateTime() {
		return endDateTime;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public Job getJob() {
		return job;
	}
	
	public ECycleState getState() {
		if(getEndDateTime()==null){
			return ECycleState.RUNNING;
		}
		return ECycleState.NOT_RUNNING;
	}

	public void setProcessedDocuments(Set<ProcessedDocument> processedDocuments) {
		this.processedDocuments = processedDocuments;
	}

	public Set<ProcessedDocument> getProcessedDocuments() {
		return processedDocuments;
	}
}

move2alf-war/src/main/java/eu/xenit/move2alf/core/dto/Job.java
package eu.xenit.move2alf.core.dto;

import eu.xenit.move2alf.common.IdObject;

import java.util.Date;
import java.util.Set;

public class Job extends IdObject {

	private String name;

	private String description;

	private UserPswd creator;

	private Date creationDateTime;

	private Date lastModifyDateTime;
	
	private ConfiguredAction firstConfiguredAction;
	
	private Set<Schedule> schedules;
	
	private Set<Cycle> cycles;

    private boolean sendReport;

    public boolean isSendReport() {
        return sendReport;
    }

    public void setSendReport(boolean sendReport) {
        this.sendReport = sendReport;
    }

    public String getSendReportTo() {
        return sendReportTo;
    }

    public void setSendReportTo(String sendReportTo) {
        this.sendReportTo = sendReportTo;
    }

    public boolean isSendErrorReport() {
        return sendErrorReport;
    }

    public void setSendErrorReport(boolean sendErrorReport) {
        this.sendErrorReport = sendErrorReport;
    }

    public String getSendErrorReportTo() {
        return sendErrorReportTo;
    }

    public void setSendErrorReportTo(String sendErrorReportTo) {
        this.sendErrorReportTo = sendErrorReportTo;
    }

    private String sendReportTo;

    private boolean sendErrorReport;

    private String sendErrorReportTo;

	public Job() {

	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

	public void setCreator(UserPswd creator) {
		this.creator = creator;
	}

	public UserPswd getCreator() {
		return creator;
	}

	public void setCreationDateTime(Date creationDateTime) {
		this.creationDateTime = creationDateTime;
	}

	public Date getCreationDateTime() {
		return creationDateTime;
	}

	public void setLastModifyDateTime(Date lastModifyDateTime) {
		this.lastModifyDateTime = lastModifyDateTime;
	}

	public Date getLastModifyDateTime() {
		return lastModifyDateTime;
	}

	public void setFirstConfiguredAction(ConfiguredAction firstConfiguredAction) {
		this.firstConfiguredAction = firstConfiguredAction;
	}

	public ConfiguredAction getFirstConfiguredAction() {
		return firstConfiguredAction;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

	public Set<Schedule> getSchedules() {
		return schedules;
	}
	
	public void setCycles(Set<Cycle> cycles) {
		this.cycles = cycles;
	}
	
	public Set<Cycle> getCycles() {
		return cycles;
	}
	
}

move2alf-war/src/main/java/eu/xenit/move2alf/web/controller/destination/model/ContentStoreModel.java
package eu.xenit.move2alf.web.controller.destination.model;

/**
 * User: Thijs Lemmens (tlemmens@xenit.eu)
 * Date: 9/11/13
 * Time: 1:38 PM
 */
public class ContentStoreModel {

    private String name;
    private int id;

    public ContentStoreModel(String name, int id) {
        this.name = name;
        this.id = id;
    }

    public int getId() {

        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {

        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

move2alf-war/src/main/java/eu/xenit/move2alf/web/controller/DestinationController.java
package eu.xenit.move2alf.web.controller;

import eu.xenit.move2alf.core.action.ClassInfoModel;
import eu.xenit.move2alf.core.dto.Resource;
import eu.xenit.move2alf.logic.DestinationService;
import eu.xenit.move2alf.logic.JobService;
import eu.xenit.move2alf.web.controller.destination.DestinationTypeController;
import eu.xenit.move2alf.web.controller.destination.ResourceTypeClassInfoService;
import eu.xenit.move2alf.web.dto.DestinationInfo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * User: Thijs Lemmens (tlemmens@xenit.eu)
 * Date: 6/10/13
 * Time: 4:33 PM
 */
@Controller
public class DestinationController extends AbstractController{

    public DestinationController(){
        super();
    }

    @Autowired
    private JobService jobService;
    private JobService getJobService(){
        return jobService;
    }

    @Autowired
    protected ResourceTypeClassInfoService resourceTypeClassInfoService;

    @Autowired
    private DestinationService destinationService;


    @RequestMapping("/destinations")
    public ModelAndView destinations() {
        ModelAndView mav = new ModelAndView();
        List<DestinationInfo> destinations = new ArrayList<DestinationInfo>();
        for(Resource resource: destinationService.getDestinations()){
            destinations.add(resourceTypeClassInfoService.getDestinationType(resource.getClassId()).getDestinationInfo(resource));
        }
        mav.addObject("destinations", destinations);
        mav.addObject("destinationOptions", getDestinationTypeMap());
        mav.addObject("role", getRole());
        mav.setViewName("manage-destinations");
        return mav;
    }

    private Map<String, DestinationTypeController> getDestinationTypeMap() {
        Map<String, DestinationTypeController> destinationTypeMap = new HashMap<String, DestinationTypeController>();
        for(ClassInfoModel model: resourceTypeClassInfoService.getClassesForCategory(ResourceTypeClassInfoService.CATEGORY_DESTINATION)){
            DestinationTypeController type = resourceTypeClassInfoService.getDestinationType(model.getClassId());
            destinationTypeMap.put(model.getClassId(), type);
        }
        return destinationTypeMap;
    }
}

move2alf-war/src/main/java/eu/xenit/move2alf/web/controller/JobController.java
package eu.xenit.move2alf.web.controller;

import eu.xenit.move2alf.common.Util;
import eu.xenit.move2alf.core.ConfigurableObject;
import eu.xenit.move2alf.core.action.ActionClassInfoService;
import eu.xenit.move2alf.core.dto.Cycle;
import eu.xenit.move2alf.core.dto.Job;
import eu.xenit.move2alf.core.dto.ProcessedDocument;
import eu.xenit.move2alf.core.dto.Resource;
import eu.xenit.move2alf.core.enums.ECycleState;
import eu.xenit.move2alf.core.enums.EProcessedDocumentStatus;
import eu.xenit.move2alf.core.sharedresource.alfresco.InputSource;
import eu.xenit.move2alf.logic.DestinationService;
import eu.xenit.move2alf.logic.JobService;
import eu.xenit.move2alf.web.controller.destination.AlfrescoDestinationTypeController;
import eu.xenit.move2alf.web.controller.destination.CastorDestinationTypeController;
import eu.xenit.move2alf.web.controller.destination.model.ContentStoreModel;
import eu.xenit.move2alf.web.dto.HistoryInfo;
import eu.xenit.move2alf.web.dto.JobModel;
import eu.xenit.move2alf.web.dto.ScheduleConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.support.PagedListHolder;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.validation.ObjectError;
import org.springframework.web.bind.ServletRequestUtils;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.*;

@Controller
public class JobController extends AbstractController{

	private static final Logger logger = LoggerFactory
			.getLogger(JobController.class);

	private JobService jobService;
    private ActionClassInfoService actionClassService;

    public ActionClassInfoService getActionClassService() {
        return actionClassService;
    }

    @Autowired
    public void setActionClassService(ActionClassInfoService actionClassService) {
        this.actionClassService = actionClassService;
    }

    @Autowired
	public void setJobService(JobService jobService) {
		this.jobService = jobService;
	}

	public JobService getJobService() {
		return jobService;
	}


	@RequestMapping("/job/dashboard")
	public ModelAndView dashboard() {
		ModelAndView mav = new ModelAndView();
		mav.addObject("jobInfoList", getJobService().getAllJobInfo());
		mav.addObject("role", getRole());
		mav.setViewName("dashboard");
		return mav;
	}

	@RequestMapping(value = "/job/create", method = RequestMethod.GET)
	public ModelAndView createJobForm() {
		ModelAndView mav = new ModelAndView("create-job");
		mav.addObject("job", new JobModel());
		
		jobModel(mav);

		return mav;
	}

	@RequestMapping(value = "/job/create", method = RequestMethod.POST)
	public ModelAndView createJob(@ModelAttribute("job") @Valid JobModel job,
			BindingResult errors) {
		
		if(getJobService().checkJobExists(job.getName())){
			errors.addError(new FieldError("job", "name", "The name you entered already exists."));
		}
		

		jobValidation(job, errors);

		if (errors.hasErrors()) {
			System.out.println("THE ERRORS: " + errors.toString());
			ModelAndView mav = new ModelAndView("create-job");
			mav.addObject("job", job);
			mav.addObject("errors", errors.getFieldErrors());
			
			jobModel(mav);

			return mav;
		}

		ModelAndView mav = new ModelAndView();
		List<String> cronJobs = job.getCron();
		int jobId = getJobService().createJob(job).getId();

		for (int i = 0; i < cronJobs.size(); i++) {
			getJobService().createSchedule(jobId, cronJobs.get(i));
		}

		mav.setViewName("redirect:/job/dashboard");
		return mav;
	}

    @Autowired
    private DestinationService destinationService;

	private void jobModel(ModelAndView mav) {
        List<ContentStoreModel> contentStores = new ArrayList<ContentStoreModel>();
        contentStores.add(new ContentStoreModel("Default Alfresco content store", -1));
        for (Resource resource: destinationService.getDestinationsForClassId(CastorDestinationTypeController.CLASS_ID)){
            contentStores.add(new ContentStoreModel(resource.getName(), resource.getId()));
        }
        mav.addObject("contentStores", contentStores);
		mav.addObject("destinations", destinationService.getDestinationsForClassId(AlfrescoDestinationTypeController.CLASS_ID));
		mav.addObject("metadataOptions", getActionClassService().getClassesForCategory(ConfigurableObject.CAT_METADATA));
		mav.addObject("transformOptions", getActionClassService().getClassesForCategory(ConfigurableObject.CAT_TRANSFORM));
		mav.addObject("role", getRole());
	}

	private void jobValidation(JobModel job, BindingResult errors) {
		List<String> metadata = job.getParamMetadata();
		Set<String> uniqueMetadataNames = new HashSet<String>();
		if (metadata != null) {
			for (int i = 0; i < metadata.size(); i++) {
				String[] metadataElements = metadata.get(i).split("\\|");
				if (metadataElements != null) {
					boolean metadataUnique = uniqueMetadataNames
							.add(metadataElements[0]);
					if (metadataUnique == false) {
						errors.addError(new FieldError("job", "paramMetadata", "The metadata parameters you entered are not unique."));
					}
				}
			}
		}

        if(job.getInputSource() == InputSource.FILESYSTEM){
           if(job.getInputFolder() == null || job.getInputFolder().isEmpty()){
               errors.addError(new FieldError("job", "inputPath", "You should at least enter 1 inputfolder, or use another input source type."));
           }
        }
		

		List<String> transform = job.getParamTransform();
		Set<String> uniqueTransformNames = new HashSet<String>();
		if (transform != null) {
			for (int i = 0; i < transform.size(); i++) {
				String[] transformElements = transform.get(i).split("\\|");
				if (transformElements != null) {
					boolean transformUnique = uniqueTransformNames
							.add(transformElements[0]);
					if (transformUnique == false) {
						errors.addError(new FieldError("job", "paramTransform", "The transformation parameters you entered are not unique."));
					}
				}
			}
		}

		List<String> inputFolder = job.getInputFolder();
		Set<String> uniqueInputFolders = new HashSet<String>();
		if (inputFolder != null) {
			for (int i = 0; i < inputFolder.size(); i++) {
				boolean inputFolderUnique = uniqueInputFolders.add(inputFolder
						.get(i));
				if (inputFolderUnique == false) {
					errors.addError(new FieldError("job", "inputFolder", "The inputfolders you entered are not unique."));
				}
			}
		}
	}

	@RequestMapping(value = "/job/{id}/edit", method = RequestMethod.GET)
	public ModelAndView editJobForm(@PathVariable("id") int id) {
        if(getJobService().getJobState(id) == ECycleState.RUNNING){
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView("redirect:/job/dashboard", model);
        }
		ModelAndView mav = new ModelAndView("edit-job");
		JobModel jobModel = getJobService().getJobConfigForJob(id);
		
		mav.addObject("job", jobModel);
		
		jobModel(mav);
		
		return mav;
	}

    @RequestMapping(value = "/job/{id}/stop", method = RequestMethod.GET)
    public ModelAndView stopJob(@PathVariable("id") int id){
        getJobService().stopJob(id);
        ModelAndView mav = new ModelAndView();
        mav.setViewName("redirect:/job/dashboard");
        return mav;
    }

	@RequestMapping(value = "/job/{id}/edit", method = RequestMethod.POST)
	public ModelAndView editJob(@PathVariable int id,
			@ModelAttribute("job") @Valid JobModel job, BindingResult errors) {

		if (!getJobService().getJob(id).getName().equals(job.getName()) && getJobService().checkJobExists(job.getName())) {
			errors.addError(new FieldError("job", "name", "The name you entered is the name of another job!"));
		}

        if (getJobService().getJobState(id) == ECycleState.RUNNING){
            errors.addError(new ObjectError("job", "The job you want to save is currently running. Please wait until the job has finished."));
        }
		
		jobValidation(job, errors);

		if (errors.hasErrors()) {
			System.out.println("THE ERRORS: " + errors.toString());
			ModelAndView mav = new ModelAndView("edit-job");
			mav.addObject("job", job);
			mav.addObject("errors", errors.getFieldErrors());
			
			jobModel(mav);

			return mav;
		}
		
		ModelAndView mav = new ModelAndView("redirect:/job/dashboard");
		Job editedJob = getJobService().editJob(job);

		handleSchedule(id, job.getCron());
		return mav;
	}

	private void handleSchedule(int id, List<String> cronJobs) {
		boolean deleteSchedule = true;

		List<String> existingCronJobs = getJobService().getCronjobsForJob(id);

		logger.debug("Existing cronjobs: " + existingCronJobs);
		logger.debug("Cronjobs given in form: " + cronJobs);


		int listSize;

		try {
			listSize = cronJobs.size();
		} catch (Exception e) {
			listSize = 0;
		}
		boolean removeEntry = false;

		for (int i = 0; i < existingCronJobs.size(); i++) {
			for (int j = 0; j < listSize; j++) {
				if (removeEntry == true) {
					removeEntry = false;
				}

				if (existingCronJobs.get(i).equals(cronJobs.get(j))) {
					cronJobs.remove(j);
					j--;
					listSize--;
					deleteSchedule = false;
					removeEntry = true;
				}

			}
			if (deleteSchedule == true) {
				int scheduleId = getJobService().getScheduleId(id,
						existingCronJobs.get(i));
				logger.debug("removing cronJob: "
						+ getJobService().getSchedule(scheduleId)
								.getQuartzScheduling());
				getJobService().deleteSchedule(scheduleId);
			}
			deleteSchedule = true;
		}

move2alf-war/src/main/java/eu/xenit/move2alf/web/controller/destination/DestinationTypeController.java
package eu.xenit.move2alf.web.controller.destination;

import eu.xenit.move2alf.core.dto.Resource;
import eu.xenit.move2alf.web.dto.DestinationInfo;

/**
 * User: Thijs Lemmens (tlemmens@xenit.eu)
 * Date: 7/2/13
 * Time: 2:33 PM
 */
public interface DestinationTypeController {

    public String getName();

    public DestinationInfo getDestinationInfo(Resource resource);

}

move2alf-war/src/main/webapp/WEB-INF/freemarker/create-job.ftl
<#include "general.ftl" />
<#include "forms.ftl" />

<@html>
<@head>
</@head>
<@bodyMenu title="Create Job">
<#include "jobform-errors.ftl" />
<form class="form-horizontal" method="post" name="createJob" action="<@spring.url relativeUrl=("/job/create") />" />
	<#include "jobform.ftl" />	
</form>

</@bodyMenu>
</@html>

move2alf-war/src/main/webapp/WEB-INF/freemarker/dashboard.ftl
<#include "general.ftl" />
<#assign activeMenu="Home" />
<@html>
<@head>
</@head>
<@bodyMenu title="Dashboard">

<script src="<@spring.url relativeUrl="/js/jquery.tablesorter.js" />"></script>
<script>
    $.tablesorter.addParser({
        // set a unique id
        id: 'date',
        is: function(s) {
            // return false so this parser is not auto detected
            return false;
        },
        format: function(s, table, cell, cellIndex) {
            var $cell = $(cell);
            return $cell.attr('date');
        },
        // set type, either numeric or text
        type: 'text'
    });


$(function() {
	$("table#dashboard").tablesorter({
		headers:{
			0:{sorter: false},
            2:{sorter: 'date'},
			4:{sorter: false},
			5:{sorter: false},
			6:{sorter: false}
		}
	});
});

function stopJob(id){
	if(confirm("Are you sure you want to stop this job?")){
		window.location.href = "<@spring.url relativeUrl="/job/" />"+id+"/stop";
	}
}
</script>

<table id="dashboard" class="table-striped wide tablesorter">
	<col class="edit-column" />
	<col />
	<col />
	<col />
	<col />
	<col class="run-column" />
	<col class="delete-column" />
	
	<thead>
		<tr>
			<th>
				<#if role=="SYSTEM_ADMIN"  || role=="JOB_ADMIN">
					<a href="<@spring.url relativeUrl="/job/create" />"><img src="<@spring.url relativeUrl="/images/add-icon.png"/>" label="Create new job" alt="Create new job" /></a>
				</#if>		
			</th>
			<th class="header">Job Name</th>
			<th class="header">Last run</th>
			<th class="header">Status</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<#list jobInfoList as jobInfo>
		<tr>
			<td>
				<#if jobInfo.scheduleState=="Not running" && (role=="SYSTEM_ADMIN"  || role=="JOB_ADMIN")>
					<a href="<@spring.url relativeUrl="/job/${jobInfo.jobId}/edit" />"><img src="<@spring.url relativeUrl="/images/edit-icon.png"/>" label="edit" alt="edit" /></a>
				</#if>
			</td>
			<td><span data-content="${jobInfo.description!?html}" rel="popover"
			    data-original-title="Description">${jobInfo.jobName?html}</span></td>
			<td date="<#if jobInfo.cycleStartDateTime?? >${jobInfo.cycleStartDateTime?string("yyyyMMddHHmmss")}<#else >0</#if>">
				<#if jobInfo.cycleStartDateTime??>
					<a href="<@spring.url relativeUrl="/job/${jobInfo.jobId}/report" />">
					<#if jobInfo.cycleStartDateTime?string("yyyyMMdd") == .now?string("yyyyMMdd") >
						Today, ${jobInfo.cycleStartDateTime?time}
					<#else>	
						${jobInfo.cycleStartDateTime}
					</#if>
					</a>
					 — ${jobInfo.nrOfDocuments} documents,
					 <span<#if (jobInfo.nrOfFailedDocuments > 0)> class="failedWarning"</#if>>${jobInfo.nrOfFailedDocuments} failed</span>
				</#if>
			</td>
			<td>${jobInfo.scheduleState!"Not running"}</td>
			<td><a href="<@spring.url relativeUrl="/job/${jobInfo.jobId}/history" />">History</a></td>
			<td>
				<#if jobInfo.scheduleState=="Not running" && (role=="SYSTEM_ADMIN"  || role=="JOB_ADMIN")>
					<a class="btn" href="<@spring.url relativeUrl="/job/${jobInfo.jobId}/cycle/run" />">RUN</a>
				</#if>
                <#if jobInfo.scheduleState=="Running" && (role=="SYSTEM_ADMIN"  || role=="JOB_ADMIN")>
                    <a class="btn btn-danger" onclick="stopJob('${jobInfo.jobId}')">STOP</a>
                </#if>
            </td>
		</tr>
		</#list>
	</tbody>
</table>
<script>
$("span[rel=popover]").popover({
	offset: 10,
	html: true
});
</script>

</@bodyMenu>
</@html>

move2alf-war/src/main/webapp/WEB-INF/freemarker/destinationform.ftl
<@labeledSingleLineTextInput label="Name" name="name" binding="destination.name" />
<@labeledInput label="Type" forId="type" >

		<#list destinationOptions?keys as destinationOption>
			<@radio name="type" value=destinationOption checked=((destinationOption_index==0 && (destinationOptions?size==1 || !destination.type??)) || destinationOption==destination.classId!"false") description=destinationOption />
		</#list>
</@labeledInput>
<#list destinationOptions?values as type>
    <#include type.viewName />
</#list>

<input class="btn btn-success" type="submit" value="Save" />
<a class="btn btn-inverse" href="<@spring.url relativeUrl="/destinations" />">Cancel</a>

move2alf-war/src/main/webapp/WEB-INF/freemarker/edit-job.ftl
<#include "general.ftl" />
<#include "forms.ftl" />

<@html>
<@head>
</@head>
<@bodyMenu title="Edit Job">

<#include "jobform-errors.ftl" />
<form class="form-horizontal" method="post" name="editJob" action="<@spring.url relativeUrl=("/job/"+job.id+"/edit") />" />
	<@spring.formHiddenInput 'job.id'/>

	<#include "jobform.ftl" />	
</form>

</@bodyMenu>
</@html>

move2alf-war/src/main/webapp/WEB-INF/freemarker/export-report-csv.ftl
Name;${job.name}
Description;${job.description}
Start time;${cycle.startDateTime?datetime}
End time;${cycle.endDateTime?datetime}
Duration;${duration}
Status;${cycle.state.displayName}
Nr. of documents;${documentListSize}
Docs / s;${docsPerSecond}

List of imported documents

Name;Processed date and time;Status
<#list processedDocuments as document>
${document.name};${document.processedDateTime?datetime};${document.status.displayName}<#list document.processedDocumentParameterSet as docParameter>;${docParameter.name}: ${docParameter.value}</#list>
</#list>

move2alf-war/src/main/webapp/WEB-INF/freemarker/report.ftl
<#include "general.ftl" />

<@html>
<@head>
</@head>
<@bodyMenu title="Report" >
<h2>${job.name?html}</h2>
<table class="small">
	<tr>
		<th>Description:</th>
		<td colspan="2">${job.description}</td>
	</tr>
	<tr>
		<th>Start time:</th>
		<td colspan="2">${cycle.startDateTime}</td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>End time:</th>
		<td>${cycle.endDateTime!}</td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>Duration:</th>
		<td>${duration}</td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<th>Nr. of documents:</th>
		<td>${documentListSize}</td>
		<th<#if (nrOfFailedDocuments > 0)> class="failedWarning"</#if>>Failed documents:</th>
		<td<#if (nrOfFailedDocuments > 0)> class="failedWarning"</#if>>${nrOfFailedDocuments}</td>
	</tr>
	<tr>
		<th>State:</th>
    	<td>${cycle.state.displayName}</td>
		<th>Docs/s:</th>
		<td>${docsPerSecond}</td>
	</tr>

</table>
<a href="<@spring.url relativeUrl=("/job/"+job.id+"/"+cycle.id+"/report/exportcsv") />" >Export to CSV</a>
<#if progress??>
<hr />
<h3>Progress</h3>
<table style="cell-spacing: 1em">
<#list progress as step>
<tr><td style="text-align: center; padding: 0 15px 0 10px;">⬇</td><td></td></tr>
<#if step.total = -1>
<tr><td style="text-align: center; padding: 0 15px 0 10px;">${step.action.description}</td><td style="color: gray;">Waiting...</td></tr>
<#else>
    <#if step.processed < step.total>
<tr><td style="text-align: center; padding: 0 15px 0 10px; font-weight: bold;">${step.action.description}</td>
    <td>Processed ${step.processed} documents out of ${step.total}</td></tr>
    <#else>
<tr><td style="text-align: center; padding: 0 15px 0 10px;">${step.action.description}</td>
    <td style="color: gray;">Processed ${step.processed} documents out of ${step.total}</td></tr>
    </#if>
</#if>
</#list>
</table>
</#if>
<hr />
<h3>Report</h3>
<table class="table-striped wide">
	<thead>
		<th>Name</th>
		<th>Processing date and time</th>
		<th>Status</th>
		<th>Parameters</th>
	</thead>
	<tbody>
		<#list processedDocuments as item>
			<tr>
                <#if item.reference?has_content>
				    <td><a href="${item.reference!}">${item.name}</a></td>
				<#else>
				    <td>${item.name}</td>
				</#if>
				<td>${item.processedDateTime}</td>
				<td>${item.status.displayName}</td>
				<td>
					<#list item.processedDocumentParameterSet as parameter>
						<p>
						    <#if parameter.name = "errormessage">
							    <strong>${parameter.name}:</strong> ${parameter.value?replace(" < ", "<br/>&lt; ")}
							<#else>
							    <strong>${parameter.name}:</strong> ${parameter.value}
							</#if>
						</p>
					</#list>
			</tr>
		</#list>
	</tbody>

</table>

<#assign pagedLink="/job/${job.id}/${cycle.id}/report">
<#include "paging.ftl" />

</@bodyMenu>
</@html>